### ISSUE TITLE
Can't install python pdal neither for deployment in production nor in a venv environment

### ISSUE THREAD

**Issue by shayannikoohemat** [PDAL/python#124]
I am trying to create a pypi package of my code with pdal dependency using `bitbucket-pipeline` and `requirements.txt`. I get the error similar to this issue: [issue66](https://github.com/PDAL/python/issues/66). I also get the same error if I try to install python pdal in a `venv` enviroment on `ubuntu 20.04` with `python3.9`. I only can make it work using conda installation `conda create --yes --name pdal-env --channel conda-forge pdal python-pdal python=3.9` but I don't want to use conda for deployment of my code. 

Here is the steps:
```
pipelines:
  branches:
    master:
      - step:
          name: Build and test
          image: python:3.9
          script:
            - apt-get update
            - apt-get install -y pdal
            - pip3 install --upgrade pip
            - pip3 install --no-cache-dir --index-url https://bitbucket:${NEXUS_PASSWORD}@nexus/repository/pypi/simple -r requirements.txt
            - make test
       - step:
       - ...
 ```
            
And my `pyproject.toml` file:
```
[build-system]
requires = [
    "scikit-build",
    "cmake",
    "ninja",
    "numpy",
    "pybind11[global]",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
```

requirement.txt file:
```
# Requirements for Python 3.9

laspy[lazrs]
numpy
pdal
```

and the ERROR I get:
```
Building wheels for collected packages: carrier
  Building wheel for carrier (pyproject.toml) ... done
  Created wheel for carrier: filename=carrier-0.1.BUILD_ID-py3-none-any.whl size=13800 
  Stored in directory: /foo/.cache/pip/wheels/85/12/71/7cda
  WARNING: Built wheel for carrier is invalid: Metadata 1.2 mandates PEP 440 version, but '0.1.BUILD-ID' is not
Failed to build carrier
ERROR: Could not build wheels for carrier, which is required to install pyproject.toml-based projects
make: *** [Makefile:7: install] Error 1
```

As you can see in the pipeline file the PDAL binaries are installed via `apt-get`. 
Any suggestion is appreciated to resolve this both locally in a `venv` environment and for deployment.
